# Generated by Django 5.2.6 on 2025-09-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="can_visit_friday",
            field=models.BooleanField(default=True, verbose_name="Fri"),
        ),
        migrations.AddField(
            model_name="customer",
            name="can_visit_monday",
            field=models.BooleanField(default=True, verbose_name="Mon"),
        ),
        migrations.AddField(
            model_name="customer",
            name="can_visit_saturday",
            field=models.BooleanField(default=False, verbose_name="Sat"),
        ),
        migrations.AddField(
            model_name="customer",
            name="can_visit_sunday",
            field=models.BooleanField(default=False, verbose_name="Sun"),
        ),
        migrations.AddField(
            model_name="customer",
            name="can_visit_thursday",
            field=models.BooleanField(default=True, verbose_name="Thu"),
        ),
        migrations.AddField(
            model_name="customer",
            name="can_visit_tuesday",
            field=models.BooleanField(default=True, verbose_name="Tue"),
        ),
        migrations.AddField(
            model_name="customer",
            name="can_visit_wednesday",
            field=models.BooleanField(default=True, verbose_name="Wed"),
        ),
        migrations.AddField(
            model_name="customer",
            name="day_constraint_type",
            field=models.CharField(
                choices=[
                    ("preferred", "Preferred Day(s)"),
                    ("required", "Required Day(s)"),
                ],
                default="preferred",
                help_text="Are the selected days a preference or a strict requirement?",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Billing rate in pounds per hour",
                max_digits=6,
            ),
        ),
    ]
