# Generated by Django 5.2.6 on 2025-09-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="is_repeat_job",
        ),
        migrations.AddField(
            model_name="job",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("weekly", "Weekly"),
                    ("bi-weekly", "Bi-weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
