# Generated by Django 5.2.6 on 2025-09-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_customer_can_visit_friday_customer_can_visit_monday_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffprofile",
            name="contracted_hours_per_day",
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="hours_friday",
            field=models.DecimalField(
                decimal_places=2, default=8.0, max_digits=4, verbose_name="Fri"
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="hours_monday",
            field=models.DecimalField(
                decimal_places=2, default=8.0, max_digits=4, verbose_name="Mon"
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="hours_saturday",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=4, verbose_name="Sat"
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="hours_sunday",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=4, verbose_name="Sun"
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="hours_thursday",
            field=models.DecimalField(
                decimal_places=2, default=8.0, max_digits=4, verbose_name="Thu"
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="hours_tuesday",
            field=models.DecimalField(
                decimal_places=2, default=8.0, max_digits=4, verbose_name="Tue"
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="hours_wednesday",
            field=models.DecimalField(
                decimal_places=2, default=8.0, max_digits=4, verbose_name="Wed"
            ),
        ),
    ]
