# Generated by Django 5.2.6 on 2025-09-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_job_is_repeat_job_job_recurrence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="recurrence",
        ),
        migrations.AddField(
            model_name="job",
            name="recurrence_frequency",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Frequency of recurrence (e.g., for 'weekly' type, a frequency of 2 means every 2 weeks)",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
