# Generated by Django 5.2.6 on 2025-09-06 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_job_recurrence_job_recurrence_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="job",
            name="end_time",
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name="job",
            name="start_time",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
