# Generated by Django 5.2.6 on 2025-09-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_job_date_alter_job_end_time_alter_job_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="job",
            name="address",
        ),
        migrations.AddField(
            model_name="customer",
            name="postcode",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="customer",
            name="street",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="town",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("gardening", "Gardening"),
                    ("landscaping", "Landscaping"),
                    ("maintenance", "Maintenance"),
                ],
                default="gardening",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
