# Generated by Django 5.2.6 on 2025-09-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_customer_postcode_alter_customer_street_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="default_duration_minutes",
            field=models.IntegerField(
                default=60, help_text="Default job duration in minutes"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="default_recurrence_frequency",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="customer",
            name="default_recurrence_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
